const $=s=>document.querySelector(s), euro=n=>'€'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
let viewer='Richard';
const finalProject=t=>t.final_project||t.project||t.proposed_project||'—';
const split=t=>`${t.proposed_richard||0}/${t.proposed_anastasia||0}/${t.proposed_jean_claude||0}% → ${t.status==='approved'?`${t.final_richard||0}/${t.final_anastasia||0}/${t.final_jean_claude||0}%`:'pending'}`;
const commission=t=>t.kind==='sale'?`€${Number(t.commission_pool||0).toFixed(2)} → R €${Number(t.commission_richard||0).toFixed(2)}, A €${Number(t.commission_anastasia||0).toFixed(2)}, J €${Number(t.commission_jean_claude||0).toFixed(2)}`:'—';
async function totals(){const r=await fetch('/api/summary');const d=await r.json();for(const [id,k] of [['company','company'],['a','A'],['b','B']])$('#'+id).textContent=euro(d[k]?.result);}
async function records(){const r=await fetch('/api/transactions?viewer='+encodeURIComponent(viewer));const d=await r.json();const rows=d.transactions||[];$('#ledgerMeta').textContent=`${rows.length} persistent record${rows.length===1?'':'s'} visible to ${viewer}.`;$('#rows').innerHTML=rows.map(t=>`<tr><td>${t.reference}</td><td>${t.submitter_name}</td><td>${t.kind}</td><td>${euro(t.amount)}</td><td>${t.proposed_project||t.project||'—'} → ${finalProject(t)}</td><td>${split(t)}<br><small>${commission(t)}</small></td><td>${t.status.replaceAll('_',' ')}</td></tr>`).join('')||'<tr><td colspan="7">No records yet.</td></tr>';};
async function refresh(){try{await Promise.all([totals(),records()])}catch(e){$('#ledgerMeta').textContent='Could not load the shared ledger: '+e.message;}}
$('#viewer').onchange=e=>{viewer=e.target.value;const manager=viewer==='Svetlana';$('#managerCard').hidden=!manager;$('#entryCard').hidden=manager;$('#scope').textContent=manager?'Manager view: all shared records, decisions, and test linking.':'Employee view: only this fictional employee’s submitted records.';refresh();};
$('#kind').onchange=e=>{$('#sale').hidden=e.target.value==='expense';$('#expense').hidden=e.target.value==='sale';};
$('#form').onsubmit=async e=>{e.preventDefault();const f=e.target,p={employee:viewer,reference:f.reference.value.trim(),kind:f.kind.value,amount:f.amount.value,customer:f.customer.value,project:f.project.value,category:f.category.value,proposedProject:f.proposedProject.value,description:f.description.value,splits:{Richard:f.richard.value,Anastasia:f.anastasia.value,'Jean-Claude':f.jean.value}};const d=await fetch('/api/transaction',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json());$('#message').textContent=d.ok?'✓ '+(d.message||p.reference+' recorded and awaiting the manager.'):'⚠ '+d.error;await refresh();};
$('#decision').onsubmit=async e=>{e.preventDefault();const f=e.target,p={actor:'Svetlana',reference:f.reference.value.trim(),finalProject:f.finalProject.value,note:f.note.value};const d=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json());$('#decisionMessage').textContent=d.ok?'✓ Decision saved and Sheets synchronization sent.':'⚠ '+d.error;await refresh();};
$('#linkForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d=await fetch('/api/link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'Svetlana',employee:f.employee.value,telegramId:f.telegramId.value.trim()})}).then(r=>r.json());$('#linkMessage').textContent=d.ok?'✓ '+d.message:'⚠ '+d.error;};
refresh();